project:
  type: website
  output-dir: docs

website:
  title: "Teaching Segregation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - covenants.qmd
      - redlining.qmd
      - urbanrenewal.qmd
      - resources.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

